import { ICareer } from './career';
import { ICity } from './city';
import { IContactsUser } from './contacts-user';
import { ICountersUser } from './counters-user';
import { ICountry } from './country';
import { ICropPhoto } from './crop-photo';
import { IEducation } from './education';
import { ILastSeen } from './last-seen';
import { IMilitary } from './military';
import { IOccupation } from './occupation';
import { IPersonal } from './personal';
import { IRelative } from './relative';
import { ISchool } from './school';
import { IUniversiti } from './universiti';

/*информация пользователя*/
export interface IUser {

  id: number;
  first_name: string;
  last_name: string;
  deactivated: string;
  hidden: number;

  about: string;
  activities: string;
  bdate: string;
  blacklisted: number;
  blacklisted_by_me: number;
  books: string;
  can_post: number;
  can_see_all_posts: number;
  can_see_audio: number;
  can_send_friend_request: number;
  can_write_private_message: number;
  career: ICareer;
  city: ICity;
  common_count: number;
  connections: string;
  contacts: IContactsUser;
  counters: ICountersUser;
  country: ICountry;
  crop_photo: ICropPhoto;
  domain: string;
  education: IEducation;
  exports: string;
  first_name_nom: string;
  first_name_gen: string;
  first_name_dat: string;
  first_name_acc: string;
  first_name_inc: string;
  first_name_abl: string;
  followers_count: number;
  friend_status: number;
  games: string;
  has_mobile: number;
  has_photo: number;
  home_town: string;
  interests: string;
  is_favorite: number;
  is_friend: number;
  is_hidden_from_feed: number;
  last_name_nom: string;
  last_name_gen: string;
  last_name_dat: string;
  last_name_acc: string;
  last_name_inc: string;
  last_name_abl: string;
  last_seen: ILastSeen;
  lists: string;
  maiden_name: string;
  military: IMilitary;
  movies: string;
  music: string;
  nickname: string;
  occupation: IOccupation;
  online: number;
  online_mobile: number;
  online_app: number;
  personal: IPersonal;
  photo_50: string;
  photo_100: string;
  photo_200_orig: string;
  photo_200: string;
  photo_400_orig: string;
  photo_id: string;
  photo_max: string;
  photo_max_orig: string;
  quotes: string;
  relatives: IRelative[];
  relation: number;
  schools: ISchool[];
  screen_name: string;
  sex: number;
  site: string;
  status: string;
  status_audio: string;
  timezone: number;
  tv: string;
  universities: IUniversiti[];
  verified: number;
  wall_comments: number;
}

